### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by zSALLAZAR** [LousWiteMC/MineUp#1]
In the settings it says mney and not money.

**Comment by LousWiteMC** [comment]
What do you mean, can u take a picture

Vào 23:51, CN, 8 thg 3, 2020 zSALLAZAR <notifications@github.com> đã viết:

**Comment by zSALLAZAR** [comment]
![20200308_221502](https://user-images.githubusercontent.com/59490940/76171344-5ce34200-618a-11ea-8283-5d9c975baa26.jpg)

in Settings at line 15

**Comment by LousWiteMC** [comment]
Hmm set it to {money}

Vào 23:51, CN, 8 thg 3, 2020 zSALLAZAR <notifications@github.com> đã viết:

**Comment by zSALLAZAR** [comment]
ok
